sonar.projectKey=gabrielcarvallho_keeplock-backend
sonar.organization=gabrielcarvallho

sonar.projectName=KeepLock Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/*.trx

sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**

sonar.language=cs