version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: keeplock-portainer
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  postgresql:
    image: postgres:latest
    container_name: keeplock-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyStrong!Passw0rd
      POSTGRES_DB: keeplock
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  seq:
    image: datalust/seq:latest
    container_name: credential-manager-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data:/data
      - seq-logs:/logs

volumes:
  data:
  seq_data:
  portainer_data: